name: stellar_wallet_flutter_sdk
description: Flutter Wallet SDK is a library that allows developers to build wallet applications on the Stellar network faster.
version: 0.2.0
homepage: https://github.com/Soneso/stellar_wallet_flutter_sdk

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  stellar_flutter_sdk:
    git:
      url: https://github.com/iampawan/stellar_flutter_sdk.git
  
  http: ^1.0.0
  jwt_decoder: ^2.0.1
  logger: ^2.0.1

